WasteManager/Controllers/IndicatorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using WasteManager.Models;
using WasteManager.Models.Context;
using WasteManager.Services;

namespace WasteManager.Controllers
{
    public class IndicatorController : Controller
    {

        private readonly WasteManagerContext _context;

        private readonly IGlobalAmbient _globalAmbient;

        public IndicatorController(WasteManagerContext context, IGlobalAmbient globalAmbient)
        {
            this._context = context;
            this._globalAmbient = globalAmbient;
        }

        // GET: Indicator
        public ActionResult Index()
        {
            return View();
        }
        

        [HttpGet]
        public ActionResult ResidueByPopulation()
        {

            return View();
        }


        [HttpPost]
        public ActionResult ResidueByPopulation([Bind("From, Until")] DateTime From, DateTime Until)
        {
            var globalCityID = this._globalAmbient.GetGlobalCityID();

            var residues = this._context.Residues.Where(r => r.Date.CompareTo(From) > 0 && r.Date.CompareTo(Until) < 0 && r.CityID == globalCityID);

            var population = this._context.Cities.FirstOrDefault(c => c.ID == globalCityID).Population;

            var teste = new Dictionary<eResidueType, double>();

            foreach(var residue in residues)
            {
                if (teste.ContainsKey(residue.Type))
                    teste[residue.Type] += residue.Quantity * 1000 / population;
                else
                    teste.Add(residue.Type, residue.Quantity * 1000 / population);
            }

            return View(teste);
        }

        public ActionResult BiogasByResidue()
        {
            return View();
        }

        public ActionResult ResiduesBYType()
        {
            return View();
        }

        public ActionResult CostsByResidue()
        {
            return View();
        }
    }
}

WasteManager/Views/Indicator/CostsByResidue.cshtml
@{
    ViewData["Title"] = "CostsByResidue";
}

<h2>CostsByResidue</h2>

WasteManager/Views/Indicator/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Indicators</h2>

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li><a asp-area="" asp-controller="Indicator" asp-action="ResidueByPopulation">Residue by population</a></li>
    </ul>
</div>

WasteManager/Views/Indicator/ResidueByPopulation.cshtml
@model Dictionary<eResidueType, double>

@{
    ViewData["Title"] = "ResidueByPopulation";
}

<h2>Residue by population</h2>

<form action="ResidueByPopulation" method="post">

    <div class="form-group">
        <label class="control-label">From:</label>
        <input class="form-control" type="date" data-val="true" data-val-required="The Date field is required." id="from" name="from" value="">
        <span class="text-danger field-validation-valid" data-valmsg-replace="true"></span>
    </div>

    <div class="form-group">
        <label class="control-label">Until:</label>
        <input class="form-control" type="date" data-val="true" data-val-required="The Date field is required." id="until" name="until" value="">
        <span class="text-danger field-validation-valid" data-valmsg-replace="true"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Send" class="btn btn-default">
    </div>

</form>

@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Residue Type</th>
                <th scope="col">Per capita amount</th>
            </tr>
        </thead>
        <tbody>


            @foreach (var residue in Model)
            {
                <tr>
                    <td>@residue.Key</td>
                    <td>@residue.Value kg</td>

                </tr>
            }

        </tbody>
    </table>
}

WasteManager/Views/Indicator/ResiduesBYType.cshtml
@{
    ViewData["Title"] = "ResiduesBYType";
}

<h2>ResiduesBYType</h2>